version: "3"

services:
  dbpostgresql:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_RANDOM_ROOT_PASSWORD: "1"
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  boring-game-server:
    build: ./boring-game-server
    depends_on:
      - dbpostgresql
    ports:
      - 3030:3030
    environment:
      MEM_ARGS: "-Xmx320m"

  boring-game-ui:
    build: ./boring-game-ui
    depends_on:
      - boring-game-server
    ports:
      - 4200:4200
    environment:
      SERVER_URL: localhost:3030
